require 'smartcore/client/validation_methods/confirm_email'
require 'smartcore/client/validation_methods/confirm_union_email'
require 'smartcore/client/validation_methods/document_scan'
require 'smartcore/client/validation_methods/social_profile'
require 'smartcore/client/validation_methods/staff_verification'
require 'smartcore/client/validation_methods/send_email'
require 'smartcore/client/validation_methods/send_sms'
require 'smartcore/client/validation_methods/confirm_phone_number'